### PR TITLE
Add animation

### PR DESCRIPTION
**Pull request by smitelij**
I wanted to add the ability to animate the clock hand when we are automatically changing the display from hours to minutes, and when we are flipping back and forth between hours and minutes.

There is still room for improvement in calculating the target degree- the intent is to never rotate more than 180degrees, but sometimes it will do more than a full rotation before landing at the target spot.

I followed the similar HTML directive pattern established.

### CODE REVIEW

**Comment by torabian** [comment]
There are so many conflicts with this, please resolve them and notify us.

**Comment by torabian** [comment]
Conflicts on this pull request are getting higher and higher. Please fix them and then we can publish this on version 1.5.3 because it's probably a useful feature.

**Comment by smitelij** [comment]
Hi,
I should be able to get around to resolving conflicts this weekend. Thank
you for your patience.

Eli

**Comment by torabian** [comment]
Thank you so much.

**Comment by smitelij** [comment]
Should be good now, sorry for the delay. Let me know if you have any concerns

**Comment by torabian** [comment]
Thank you for this contribution. It will be available from `1.6.0` onward on npm.

**Pull request merged**
