### PR TITLE
Add rxjs 6 and rxjs-compat

### PR DESCRIPTION
**Pull request by torabian**
This will extend support for Angular 6, by upgrading rxjs to version 6, and installing rxjs-compat.

### CODE REVIEW

**Comment by Chris2011** [comment]
@yousefsami smth missing here? Maybe checking the tests, then you can merge it please?

**Comment by Chris2011** [comment]
@yousefsami will ping it up again.

**Comment by torabian** [comment]
Sorry for being late. I am looking forward to merge this today. In fact, I am not sure if I can keep backward compatibility.

**Comment by torabian** [comment]
Now it's available for Angular 6, 7 from version `1.8.0`

**Comment by Chris2011** [comment]
@torabian better to late than never ;). thx :)

**Pull request merged**
